### ISSUE TITLE
Create a ReadMe

### ISSUE THREAD

**Issue by AgPriyanshu18** [bsoc-bitbyte/busify-android#1]
Create a Readme, explaining its features.

[Figma designs ](https://www.figma.com/file/Kjmx7bRYRvUiwUPY2CCpW2/busifyAndroid?type=design&node-id=0-1&t=tbTtmCJZTa0KNzop-0)

Tech Stack - 
Kotlin
XML
Dagger-Hilt

MVVM architecture

**Comment by Abraham12611** [comment]
Hello, I am willing to help. But I think I might need a little extra information.

**Comment by Adi8712** [comment]
Hello @AgPriyanshu18 @PraneGIT, I am willing to take up this issue

**Comment by AgPriyanshu18** [comment]
@Abraham12611 This is a college-only project, we can't assign it to you.

**Comment by aarav0012** [comment]
hello @AgPriyanshu18 @PraneGIT , I am willing to work on this issue.
I will include about the app, figma design and final look of UI , its tech stack , features and contribution guidelines.  Could you please assign it to me

**Comment by PraneGIT** [comment]
@aarav0012 @Adi8712 take reference from busify's website readme and elaborate what are you willing to write

**Comment by adityakgupta** [comment]
Hello @AgPriyanshu18 @PraneGIT, I am willing to take up this issue, sections mentioned will include:
About the app - for whom it was built and the need for taking up this project
UI - consisting of final look of the UI including images and gifs
Tech Stack - this section is all about the technologies used to build the app and what issues they target
Features - bullet points about what the capabilities of the app are
Installation - how to locally clone the project and contribute to it
Contributors - a section dedicated to those who built the app

**Comment by sadvika05** [comment]
Hey @AgPriyanshu18 @PraneGIT, I'll provide the setup steps,how to modify settings,contribution guidelines and clear overview of busify app.Can I be assigned to create the README file for this project?

**Comment by Agrim2112** [comment]
Hello @PraneGIT @AgPriyanshu18 , I am willing to take up this issue. I'll be giving a brief overview of the app, the project status, installation guide, the issues it intends to solve and a list of the key features attached with the images of the ui.

**Comment by PraneGIT** [comment]
@Adi8712 you can work on it
