### ISSUE TITLE
Implement ViewBinding

### ISSUE THREAD

**Issue by AgPriyanshu18** [bsoc-bitbyte/busify-android#14]
Implement view binding in Home, PassengerList, and OR Activity.

First, add build feature in build.gradle, then add binding in all activities.
Keep the name of the variable binding only.

**Comment by adityakgupta** [comment]
@AgPriyanshu18 @PraneGIT I would like to take up this issue, do you want me to pass binding.root to setContentView or should I just inflate the binding

**Comment by PraneGIT** [comment]
@Adi8712  go ahead,pass binding.root to setContentView
just make sure you are not changing other code ,hope that issue is resolved
