### ISSUE TITLE
[Feature Request]: Implement Recyclerview Adapter for HomeActivity 

### ISSUE THREAD

**Issue by PraneGIT** [bsoc-bitbyte/busify-android#15]
### Is your feature request related to a problem? Please describe.

Need to make adapters which generate and manage items in our Recycler View

### Describe the solution you'd like

- [ ] implement the HomeRVAdapter class for RecyclerView,make sure to use  list of **HomeRVModel** as input for your home_items.xml view.

- [ ] create a function setupRV(), in which call the adapter for the Recycler View ,use the dummy data provided as **homeRVData**, implement it's manager.

### Developer Help

for recycler view [reference ](https://androidgeek.co/recyclerview-in-android-with-example-in-depth-guide-94462a6b573b)

**Comment by sadvika05** [comment]
@PraneGIT @AgPriyanshu18 can I work on it after #18

**Comment by PraneGIT** [comment]
ok @sadvika05 you may work on it

**Comment by sadvika05** [comment]
@PraneGIT made it, kindly review.
