### ISSUE TITLE
Implement QR scanning feature

### ISSUE THREAD

**Issue by AgPriyanshu18** [bsoc-bitbyte/busify-android#16]
In the given [figma](https://www.figma.com/file/Kjmx7bRYRvUiwUPY2CCpW2/busifyAndroid?type=design&node-id=0-1&t=tbTtmCJZTa0KNzop-0), tapping on QR icon will open a scanner - 
1. The successful scan will lead to PassengerList Activity and toast the result of the scan.
2. On failure, return to Home Activity and toast scanning failed.

You can use any source to understand how to implement BarCode Scanner.
You can refer to [this ](https://harshitabambure.medium.com/barcode-scanner-and-qr-code-scanner-android-kotlin-b911b1299f65)medium article.
I also have prepared a similar short project, you can use it for [reference](https://github.com/AgPriyanshu18/BarCode_Scanner).

**Comment by Agrim2112** [comment]
@AgPriyanshu18 @PraneGIT I would like to take up this issue. I will be implementing the Zxing library for the QR scanner to open when QR icon is tapped. If required, additional features like auto focus can also be added. Alternatively, Code Scanner library which is based on Zxing can also be used. Can you please assign it to me?

**Comment by AgPriyanshu18** [comment]
Go ahead @Agrim2112, you can start working on the issue.
Do take care of lifecycle management.
