### ISSUE TITLE
[Feature Request]: Implement Recyclerview Adapter for PassengerListActivity

### ISSUE THREAD

**Issue by PraneGIT** [bsoc-bitbyte/busify-android#17]
### Is your feature request related to a problem? Please describe.

Need to make adapters which generate and manage items in our Recycler View

### Describe the solution you'd like

- [x] implement the PassengerRVAdapter class for RecyclerView,make sure to use list of PassengerRVModel as input for your activity_passenger_list.xml view.

- [x] create a function setupRV(), in which call the adapter for the Recycler View ,use the dummy data provided as passengerRVData, implement it's manager

### Developer Help

for recycler view [reference](https://androidgeek.co/recyclerview-in-android-with-example-in-depth-guide-94462a6b573b)

**Comment by adityakgupta** [comment]
@PraneGIT @AgPriyanshu18 Even though #14 has not been assigned to me, I have already finished it and will generate the pr after its assigned to me and so I would like to take up this issue and ask for a correction in #17 and #18, both of these issues have their separate view files passengerlist_items.xml and qr_items.xml respectively but home_items.xml is mentioned in the issue.

**Comment by PraneGIT** [comment]
@Adi8712 thanks for correction in the issues, will assign you this after #14

**Comment by adityakgupta** [comment]
![Screenshot 2023-07-04 144902](https://github.com/bsoc-bitbyte/busify-android/assets/116958420/2641fe13-3906-4e0e-90b0-b525571c185c)
The PassengerRVModel data class has only two variables name and isVerified, but the passengerlist_items requires 3 inputs name,info and verification should I add "val info: String" to the data class

**Comment by PraneGIT** [comment]
leave any info to default text @Adi8712, we'll change it once our backend is ready
