### ISSUE TITLE
[Feature Request]: Implement Recyclerview Adapter for QrActivity

### ISSUE THREAD

**Issue by PraneGIT** [bsoc-bitbyte/busify-android#18]
### Is your feature request related to a problem? Please describe.

Need to make adapters which generate and manage items in our Recycler View

### Describe the solution you'd like

- [ ] implement the QrRVAdapter class for RecyclerView, make sure to use list of PassengerRVModel as input for your qr_items.xml view.
- [ ] create a function setupRV(), in which call the adapter for the Recycler View ,use the dummy data provided as passengerRVData, implement it's manager

### Developer Help

for recycler view [reference](https://androidgeek.co/recyclerview-in-android-with-example-in-depth-guide-94462a6b573b)

**Comment by sadvika05** [comment]
@AgPriyanshu18 @PraneGIT, I will add QrRVAdapter class and give input according to PassengerRVModel and create a function and call the adapter for the RecyclerView . can I get assigned?

**Comment by PraneGIT** [comment]
@sadvika05 allright, just make sure you have pulled the changes before working on it

**Comment by sadvika05** [comment]
@PraneGIT @AgPriyanshu18 I have made , kindly review it.
