### ISSUE TITLE
XML for QR activity: 

### ISSUE THREAD

**Issue by PraneGIT** [bsoc-bitbyte/busify-android#5]
### Is your feature request related to a problem? Please describe.

Create the XML layout for QRActivity, take reference form frame 3 of [Figma](https://www.figma.com/file/Kjmx7bRYRvUiwUPY2CCpW2/busifyAndroid?type=design&node-id=0-1&t=Pnc9yf0QOGCtIEdo-0).

### Describe the solution you'd like

Points to consider:

Use Constraint Layout (Make sure the layout is responsive to other screen sizes).
Do not make RecyclerView time layout for this issue, just add a RecyclerView there.

**Comment by Agrim2112** [comment]
@PraneGIT @AgPriyanshu18 I would like to work on this issue. As mentioned, I would make the layout responsive to different screen sizes using Constraint Layout and will ensure that the layout is in accordance with the figma design.  Can you please assign it to me

**Comment by AgPriyanshu18** [comment]
@Agrim2112 go ahead, I'm assigning this issue to you. Only focus on XML.
