### ISSUE TITLE
Layout for PassengerList Activity

### ISSUE THREAD

**Issue by AgPriyanshu18** [bsoc-bitbyte/busify-android#6]
### Is your feature request related to a problem? Please describe.

Create XML layout for Passenger List Activity, take reference from frame 4 of [Figma](https://www.figma.com/file/Kjmx7bRYRvUiwUPY2CCpW2/busifyAndroid?type=design&node-id=0-1) 

### Describe the solution you'd like

Points to consider:
1. Use Constraint Layout (Make sure the layout is responsive to other screen sizes).
2. Do not make RecyclerView time layout for this issue, just add a RecyclerView there.

**Comment by sadvika05** [comment]
@AgPriyanshu18 @PraneGIT, I'll use constraint layout and make it responsive to all screen sizes and make layout according to the figma design. Can I get assigned to work on this?

**Comment by AgPriyanshu18** [comment]
@sadvika05  You can work on this issue. Comment here if you need any help.
