### ISSUE TITLE
XML for Recycler View Item in QR and Passenger Avtivity

### ISSUE THREAD

**Issue by AgPriyanshu18** [bsoc-bitbyte/busify-android#7]
### Is your feature request related to a problem? Please describe.

Create XML layout for recycler view item for passenger list in QR Activity and Passenger List Activity.

### Describe the solution you'd like

You need to make two layout files one for each activity. 

Points to consider:
1.Use constraint layout.
2.Make sure to wrap all views in the item.

**Comment by adityakgupta** [comment]
@PraneGIT @AgPriyanshu18 Can I work on this issue? I have already taken up issue #3 which is very similar to this, I will make sure the xml is as close to the figma design as possible, and also responsive enough to work on most screens

**Comment by PraneGIT** [comment]
@Adi8712 ok do it
